import React from 'react';

const AboutSection = () => {
  return (
    <section id="about" style={{ padding: '2rem', backgroundColor: '#f9f9f9' }}>
      <div style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center' }}>
        <h2>About Us</h2>
        <p className="bg-cover bg-fixed before:content-[''] before:absolute before:inset-0 before:bg-black before:bg-opacity-70 before:z-0 relative">
          Welcome to Noriega Law! We are dedicated to providing exceptional legal services to our clients.
          Attorney Chris Noriega’s journey into the law began shortly after he graduated from high school in 1980 and enlisted in the United States Marine Corps. While a Marine at Camp Pendleton, Chris attended Mira Costa Community College in Oceanside, California and took a variety of courses. One course that sparked his interest was an Administration of Justice class; a law-related subject.  Chris was later deployed to Okinawa, Japan where he continued to take more law-related courses that were offered by Los Angeles Metropolitan College’s satellite campus located at the Kadena Air Force Base in Okinawa. 
Chris ultimately was Honorably Discharged from the Marine Corps as a Non-Commissioned Officer (E-4) in 1986.  Shortly after his discharge, Chris acquired ownership of Noriega Bail Bonds, a business his father established in 1968. At this time, Chris was a single-parent with sole custody of his two young daughters. Nevertheless, he continued pursuing his education and eventually graduated from UCLA with a Bachelor’s Degree in Political Science in 1990.  
Chris spent the next several years raising his children and running Noriega Bail Bonds both as a bail agent and bounty hunter for his business.  As a result, Chris became intimately familiar with California’s criminal justice system. As a licensed bail agent/bounty hunter, Chris often found himself in court regarding his bail bond clients. Unlike most bail agents, Chris would often prepare, file, and argue bail motions in court on behalf of his business rather than hire an attorney. During this time, many of Chris’ bail clients would often complain to him about the poor representation they were receiving from their criminal defense attorneys who often were general practice attorneys that dabbled in numerous areas of law in addition to criminal defense.  Chris realized there was a need for an honest and competent attorney who focused solely on criminal defense in his community. Consequently, Chris decided to return to school. 
 In 1999, Chris enrolled at Western State University College of Law, the oldest law school in Orange County. While attending law school, Chris was on the Honor Roll, earned the prestigious Witkin Award for Academic Excellence in Advocacy, and received a Certificate of Criminal Law for his concentration on criminal studies. Chris also was a member of the school’s Mock Trial Team and received the Academy of Appellate Lawyers Award for brief writing in the 2002 Roger J. Traynor California Moot Court Competition held at Pepperdine University in Malibu. 
Attorney Chris Noriega established the Law Offices of Chris Noriega not long after earning his law degree in 2003.  Due to his 20-plus years working in the criminal justice system as a bail agent/bounty hunter and a desire of not wanting to be a “Jack of All Trades and Master of None,” Chris chose to focus his practice 100% on criminal defense.  


Over the years Chris has successfully handled just about every type of criminal case imaginable from low-level misdemeanors to hardcore felony cases with possible life sentences and has done so in virtually every Southern California County, including Los Angeles County, Orange County, San Bernardino County, Riverside County, and San Diego County. Specifically, he has represented clients in cases involving attempted murder, carjacking, gang cases, attempted rape, sexual assault, child molestation, false imprisonment, assault with great bodily injury (GBI), domestic violence, resisting arrest, battery on a police officer, grand theft, burglary, robbery, embezzlement, possession with intent to sell, and DUIs, just to name a few. 
Chris’ sole focus on criminal defense has resulted in a proven track record that has earned the respect of both prosecutors and judges, as well as his peers in the criminal defense bar. He is an experienced trial attorney who has established a reputation for not being afraid to take a case to trial yet knows when it is in the client’s best interests to negotiate the best possible plea deal.  As a former U.S. Marine, Chris has the grit and “can do” attitude to take on any challenge in the courtroom on behalf of his clients.
In addition to post-arrest representation, Chris also provides effective legal representation at the pre-arrest/pre-complaint stage of a police investigation.  Police often try to lure a suspect into talking with them without an attorney being present when there is not enough evidence to make an arrest. This is a crucial stage that requires competent and aggressive legal representation.   
When Chris is not in court, he frequently participates in various outreach programs to help at-risk youth and young adults. He has been an invited guest speaker on multiple occasions with the Los Angeles Sheriff Department’s Emerging Leaders Program that was created to help adults transition back into society after being released from prison.  Chris was also named Mentor of the Year for his work with the VIP Mentors Program sponsored by the State Bar of California for mentoring youth who were recently released from juvenile detention. 
Chris also regularly participates in continuing legal education courses to keep current with the latest cases, defense strategies, and tactics that have a direct impact on his clients’ cases. He has attended the highly-respected Trial Practice Institute Program at the National Criminal Defense College in Macon, GA, and is a current member of the Criminal Law Section with the State Bar of California.  
Call Attorney Chris Noriega now to take advantage of his 20 years of experience in criminal defense to help you with your case.  With his knowledge and decades of experience as a criminal defense attorney, Attorney Noriega will work hard to try to help you avoid jail time or criminal penalties or negotiate the best possible plea deal to minimize your legal exposure.
Call 626-336-8080 to schedule a FREE in-office consultation to discuss your case with Chris.  You’ll be glad you did. 

        </p>
        <p>
          At Noriega Law, we believe in building strong relationships with our clients, offering personalized
          solutions, and delivering results. Your success is our priority.
        </p>
      </div>
    </section>
  );
};

export default AboutSection;